name: data_check
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas  # Remove version pinning
  - scikit-learn
  - scipy   # Remove version pinning
  - pytest  # Consider removing this if not essential
  - pip
  - pip:
    - wandb
    - mlflow
    - hydra-core